apiVersion: v2
name: drone
description: Drone is a self-service Continuous Delivery platform for busy development teams
type: application
version: 0.2.0
appVersion: 2.2.0
kubeVersion: "^1.13.0-0"
home: https://drone.io/
icon: https://docs.drone.io/logo.svg
keywords:
  - continuous-delivery
  - continuous-deployment
  - continuous-integration
  - docker
  - drone
  - drone.io
  - go
sources:
  - https://github.com/drone/drone
  - https://github.com/drone/charts
maintainers:
  - name: Drone
    email: hello@drone.io
