apiVersion: v2
name: drone-runner-kube
description: The Drone Kubernetes runner launches builds in Kubernetes Jobs
type: application
version: 0.3.0
appVersion: 1.0.0
kubeVersion: "^1.13.0-0"
home: https://docs.drone.io/runner/kubernetes/
icon: https://docs.drone.io/logo.svg
keywords:
  - continuous-delivery
  - continuous-deployment
  - continuous-integration
  - docker
  - drone
  - drone.io
  - go
sources:
  - https://github.com/drone-runners/drone-runner-kube
  - https://github.com/drone/charts
maintainers:
  - name: Drone
    email: hello@drone.io
